apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-calender-application
  namespace: new-calender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-calender-application
  template:
    metadata:
      labels:
        app: new-calender-application
    spec:
      containers:
        - name: new-calender-application
          image: bahavathyacr.azurecr.io/new-calender-app:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__DefaultConnection
              value: "Data Source=/app/appointments.db"
---
apiVersion: v1
kind: Service
metadata:
  name: new-calender-service
  namespace: new-calender
spec:
  type: LoadBalancer
  selector:
    app: new-calender-application
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: new-calender-ingress
  namespace: new-calender
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: calender.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: new-calender-service
                port:
                  number: 80
